### ISSUE TITLE
This is madness

### ISSUE THREAD

**Issue by zeroedin-bill** [ircmaxell/PhpGenerics#3]
![this is php](http://www.reactiongifs.com/r/2012/03/Sparta.gif)

**Comment by FGRibreau** [comment]
:+1: ^^

**Comment by galves** [comment]
Madness or Genius?

**Comment by haskellcamargo** [comment]
Somethings are made not because the should be made but because they can be made.

**Comment by ircmaxell** [comment]
I make no claim of sanity.
