### ISSUE TITLE
Can you make this into a PECL extension?

### ISSUE THREAD

**Issue by HallofFamer** [ircmaxell/PhpGenerics#5]
I very like your implementation for PHP generics, and it's amazing you did this with PHP rather than native C code. Still, I think it's a good idea to port it to C, and publish it as a PECL extension? Is this doable? Once PHP 7 comes out I plan to run a customized version of it on my server, to test out some features, I definitely would love to have Generics on it. Thanks!

**Comment by raoulvdberge** [comment]
It would be awesome if it would be a feature of PHP 7.1.

**Comment by ircmaxell** [comment]
No, it's not possible to do this in an extension since it uses a modified parser (well, you *could*, but you'd contain a duplicate parser). To implement this properly would require changes to the engine.
